### Developer: Edgar Moises Hernandez-Gonzalez
### Numpy

In [1]:
!python --version

Python 3.7.11


In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.5'

In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = np.array([
              [1,2,3,],
              [4,5,6,],
              [7,8,9,],
              [0,-1,-2,],
              ])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, -1, -2]])

In [6]:
type(x)

numpy.ndarray

In [7]:
len(x)

4

In [8]:
x.shape

(4, 3)

In [9]:
x.ndim

2

In [10]:
x[1,2]

6

In [11]:
np.sum(x)

42

In [12]:
# columnas
np.sum(x, axis=0)

array([12, 14, 16])

In [13]:
# filas
np.sum(x, axis=1)

array([ 6, 15, 24, -3])

In [14]:
np.min(x)

-2

In [15]:
np.mean(x)

3.5

In [16]:
np.std(x)

3.452052529534663

In [17]:
abc = np.array([
                [1,2,4],
                [3,4,0],
                [8,2,1]
                ])

In [18]:
np.unique(abc)

array([0, 1, 2, 3, 4, 8])

In [19]:
matriz = np.random.rand(4,5)
matriz

array([[0.86041451, 0.44224613, 0.53386606, 0.37496144, 0.22507822],
       [0.40882568, 0.58349727, 0.72623337, 0.19721584, 0.3024334 ],
       [0.97720698, 0.94610024, 0.98624045, 0.91067662, 0.07742851],
       [0.04992104, 0.60643123, 0.80674375, 0.55511196, 0.00161747]])

In [20]:
matriz*=2
matriz

array([[1.72082901, 0.88449227, 1.06773212, 0.74992288, 0.45015644],
       [0.81765137, 1.16699454, 1.45246673, 0.39443167, 0.60486679],
       [1.95441397, 1.89220049, 1.97248091, 1.82135323, 0.15485701],
       [0.09984208, 1.21286246, 1.61348749, 1.11022391, 0.00323493]])

In [21]:
np.ceil(matriz)

array([[2., 1., 2., 1., 1.],
       [1., 2., 2., 1., 1.],
       [2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 1.]])

In [22]:
np.floor(matriz)

array([[1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.]])

In [23]:
np.round(matriz)

array([[2., 1., 1., 1., 0.],
       [1., 1., 1., 0., 1.],
       [2., 2., 2., 2., 0.],
       [0., 1., 2., 1., 0.]])

In [24]:
matrizA = np.random.randint(10, size=(3,3))
matrizA

array([[7, 3, 7],
       [4, 5, 1],
       [7, 7, 3]])

In [27]:
matrizB = np.arange(9).reshape(3,3)
matrizB

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
matrizA + matrizB

array([[ 7,  4,  9],
       [ 7,  9,  6],
       [13, 14, 11]])

In [29]:
matrizA - matrizB

array([[ 7,  2,  5],
       [ 1,  1, -4],
       [ 1,  0, -5]])

In [31]:
np.dot(matrizA, matrizB)

array([[51, 68, 85],
       [21, 31, 41],
       [39, 56, 73]])

In [32]:
np.dot(matrizB, matrizA)

array([[ 18,  19,   7],
       [ 72,  64,  40],
       [126, 109,  73]])

In [33]:
np.transpose(matrizB)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [34]:
np.linalg.det(matrizA)

-7.999999999999995

In [35]:
np.linalg.inv(matrizA)

array([[-1.   , -5.   ,  4.   ],
       [ 0.625,  3.5  , -2.625],
       [ 0.875,  3.5  , -2.875]])

In [37]:
matrizA**2

array([[49,  9, 49],
       [16, 25,  1],
       [49, 49,  9]])

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.concatenate((matrizA, matrizB))

array([[7, 3, 7],
       [4, 5, 1],
       [7, 7, 3],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
np.concatenate((matrizA, matrizB), axis=1)

array([[7, 3, 7, 0, 1, 2],
       [4, 5, 1, 3, 4, 5],
       [7, 7, 3, 6, 7, 8]])

In [43]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.where(b < 5, b*2, b*10)

array([ 0,  2,  4,  6,  8, 50, 60, 70, 80, 90])

In [45]:
y = np.arange(16)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
z = y.reshape(4,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
z.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [48]:
z.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
A = np.random.rand(8)
A

array([0.81996209, 0.11570988, 0.9814125 , 0.24212415, 0.22275101,
       0.54851399, 0.83412397, 0.25784081])

In [50]:
np.argmax(A)

2

In [51]:
edades = [12, 15, 13, 12, 18, 20, 19, 20, 13, 12, 13, 17, 15, 16, 13, 14, 13,
          17, 19]

In [52]:
np.sort(edades)

array([12, 12, 12, 13, 13, 13, 13, 13, 14, 15, 15, 16, 17, 17, 18, 19, 19,
       20, 20])

In [53]:
frecuencias, extremos = np.histogram(edades, bins=8)
print(frecuencias, extremos)

[3 5 1 2 1 2 1 4] [12. 13. 14. 15. 16. 17. 18. 19. 20.]
